apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-08-29T05:58:17Z
  labels:
    app: grafana
    chart: grafana-1.0.1
    heritage: Tiller
    release: istio
  name: grafana-svc
  namespace: istio-system
  resourceVersion: "10889"
  selfLink: /api/v1/namespaces/istio-system/services/grafana
  uid: 86819d24-ab50-11e8-86b2-00163e10b085
spec:
  ports:
  - name: http
    port: 3000
    nodePort: 30003
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
