apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-08-29T05:58:17Z
  labels:
    app: servicegraph
    chart: servicegraph-1.0.1
    heritage: Tiller
    release: istio
  name: servicegraph-svc
  namespace: istio-system
  resourceVersion: "10915"
  selfLink: /api/v1/namespaces/istio-system/services/servicegraph
  uid: 868ffa2b-ab50-11e8-86b2-00163e10b085
spec:
  ports:
  - name: http
    port: 8088
    nodePort: 30004
    protocol: TCP
    targetPort: 8088
  selector:
    app: servicegraph
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
